name: unit-tests

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    unit-tests:
        runs-on: ubuntu-latest

        container:
            image: epitechcontent/epitest-docker
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: run the tests
              run: |
                make tests_run
